# Generated by Django 3.2.15 on 2022-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
