# Generated by Django 3.2.15 on 2022-09-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_photo_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='caption',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
