# Generated by Django 3.2.15 on 2022-10-30 14:04

from django.db import migrations, models
import django.db.models.deletion
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_remove_photo_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting', models.ForeignKey(default=work.models.get_last_painting, on_delete=django.db.models.deletion.CASCADE, to='work.painting')),
            ],
        ),
    ]
