# Generated by Django 3.2.15 on 2022-10-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_mainpainting'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='painting',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
